# -*- coding: utf-8 -*-
"""2.15 Exercises.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZrlLxG6BwoRf6RkXkbdxskIUGIZarpHC
"""

#Exercise 2: Write a program that uses input to prompt a user for their
#name and then welcomes them.

#Enter your name: Chuck
#Hello Chuck

#CODE
name = input('Enter your name: ')
print('Hello ' + name)

#Exercise 3: Write a program to prompt the user for hours and rate per
#hour to compute gross pay.

#Enter Hours: 35
#Enter Rate: 2.75
#Pay: 96.25

#CODE
hours = float(input('Enter Hours: '))
rate = 2.75
pay = hours * rate
print(pay)

#Exercise 4: Assume that we execute the following assignment statements:

#width = 17
#height = 12.0

#CODE
width = 17
height = 12.0

print(width//2)
print(width/2)
print(height/3)
print(1 + 2 * 5)

#Exercise 5: Write a program which prompts the user for a Celsius temperature, convert the temperature to Fahrenheit, and print out the
#converted temperature.

#CODE
celcius = float(input('Enter Temperature(Celcius): '))
print(celcius * 1.8 + 32)